MasterSite/masterusers/urls.py
from django.urls import path

# ================ imports from current app
from . import views as user_web_views

# ================== app's name ================

app_name = "masteruser"
urlpatterns = [
    # =========================== profile =====================
    path('master/user/profile',user_web_views.profile,name="profile"),

    # =================== subjects learns =============================
    path('master/user/subjects/<int:subject_id>/learns',user_web_views.topics_and_lessions,name='topics_lessions'),
    path('master/user/subject/<int:topic_id>/topic/add',user_web_views.add_lession,name="add_new_lession"),
    path('master/user/subjects/lession-<int:lession_id>/details',user_web_views.lession_details,name="lession_details"),
    path('master/user/subject/lession-<int:lession_id>/edit',user_web_views.edit_learns,name="edit_lession"),
    path('user/topic/<int:topic_id>/delete',user_web_views.delete_topic,name='delete_topic'),
    path('user/lession/<int:lession_id>/remove',user_web_views.delete_lession,name="delete_lession"),

]

MasterSite/masterweb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("masterwebsite.urls")),
    path('master/users',include("masterusers.urls")),
    path('ckeditor/',include("ckeditor_uploader.urls")),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MasterSite/masterusers/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
# ++++++++++++++++++++++++++++++++ user learns models here +++++++++++++++++++++++++++++++++++++++= 

class Subject(models.Model):
    """ A subject taken by a user"""
    # User models as a foreign key to this model
    name = models.CharField("Subject Name:",max_length=25,null=False,blank=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Topic(models.Model):
    """ Top learned by the user """
    # Subject model as a foreign key to this model
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    topic_name = models.CharField("Topic Name",max_length=25,null=False,blank=False)
    dateAdded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.topic_name



class Learn(models.Model):
    """ learns of the day can be saved into user account through subject"""
    # topic model as a foriegn key to this model
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    lession_type = models.CharField(max_length=24,null=False,blank=False)
    lession = RichTextUploadingField(null=True,blank=True,config_name='special')
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.lession_type

MasterSite/masterusers/forms.py
from django import forms
# ================ user learns models import ===programming questions models import =======
from .models import (
                    # ================ user learns models import
                    Subject,
                    Topic,
                    Learn,
)

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name']


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['topic_name']


class LearnForm(forms.ModelForm):
    class Meta:
        model =Learn
        fields =['lession_type','lession']

MasterSite/masterusers/views.py
from django.shortcuts import render,redirect,get_object_or_404

# Create your views here.

# Create your views here.
from .models import (
                    # ========= user learns models ===============
                    Subject,
                    Topic,
                    Learn,
                    )
from .forms import (
                    SubjectForm,
                    TopicForm,
                    LearnForm,
                    )

def profile(request):
    """ user profile page is rendered here"""
    subjects = Subject.objects.order_by('-date_added').all()
    if request.method == "POST":
        form = SubjectForm(request.POST)
        if form.is_valid() and form is not None:
            form.save()
            return redirect("masteruser:profile")
    else:
        form = SubjectForm()

    context = {
        "subjects":subjects,
        "form":form,
    }
    return render(request,'masterusers/profile.html',context)


def topics_and_lessions(request,subject_id):
    """Go to the particular subject requested for details"""
    subject_details = get_object_or_404(Subject,pk=subject_id)
    topics = subject_details.topic_set.all()
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid() and form is not None:
            new_topic = form.save(commit=False)
            new_topic.subject = subject_details
            new_topic.save()
            return redirect('masteruser:topics_lessions',subject_details.id)
    else:
        form = TopicForm()

    context = {
        "topics":topics,
        "subject":subject_details,
        'form':form,
    }
    return render(request,'masterusers/topic_and_lessions.html',context)


def add_lession(request,topic_id):
    """ add lessions learned to a topic learned about"""
    topics = get_object_or_404(Topic,pk=topic_id)
    subject = topics.subject.id
    if request.method == "POST":
        form = LearnForm(request.POST)
        if form.is_valid() and form is not None:
            new_lession = form.save(commit=False)
            new_lession.topic = topics
            new_lession.save()
            return redirect("masteruser:topics_lessions",subject)
    else:
        form = LearnForm()
    context = {
        "topic":topics,
        "form":form,
        "subject":subject,
    }
    return render(request,"masterusers/add_new_lession.html",context)


def lession_details(request,lession_id):
    """ get the detail information about the lession"""
    lession = get_object_or_404(Learn,pk=lession_id)
    context = {
        'lession':lession,
        'topic_lession':lession.topic,
    }
    return render(request,'masterusers/lession_details.html',context)


def edit_learns(request,lession_id):
    """ edit lessions learn to add or remove text"""
    lession_learned = get_object_or_404(klass=Learn,pk=lession_id)
    if request.method == "POST":
        form = LearnForm(instance=lession_learned,data=request.POST)
        if form.is_valid() and form is not None:
            form.save()
            return redirect("masteruser:topics_lessions",lession_learned.topic.subject.id)
    else:
        form = LearnForm(instance=lession_learned)
    context = {
        "form":form,
        'lession':lession_learned,
    }
    return render(request,"masterusers/edit_lession.html",context)

def delete_topic(request,topic_id):
    """ delete item from data base"""
    topic = get_object_or_404(Topic,pk=topic_id)
    topic.delete()
    return redirect("masteruser:topics_lessions",topic.subject.id)

def delete_lession(request,lession_id):
    """ delete item from data base"""
    lession = get_object_or_404(Learn,pk=lession_id)
    lession.delete()
    return redirect("masterusers:topics_lessions",lession.topic.subject.id)

MasterSite/masterusers/templates/masterusers/add_new_lession.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}new lession{% endblock title %}

<!-- body -->
{% block body %}
<div class="new-lession-section">
    <a href="{% url 'masteruser:topics_lessions' subject %}">{{topic.topic_name}}</a>
</div>
<div class="new-lession-form">
    <form action="{% url 'masteruser:add_new_lession' topic.id %}" method="POST">
        {% csrf_token %}
        <!--  -->
        {{form.media}}
        <!--  -->
        {{form.as_p}}
        <!--  -->
        <input class="btn btn-success col-12 col-lg-2" type="submit" value="Add" />
    </form>
</div>
<!--  -->
{% endblock body %}

MasterSite/masterusers/templates/masterusers/edit_lession.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}edit-lession-type{% endblock title %}

<!-- body -->
{% block body %}
<div class="text">
    <a class="text-center text-primary" href="{% url 'masteruser:profile' %}"> profile</a>
</div>
<div class="edit-content">
    <section class="edit-form">
        <form action="{% url 'masteruser:edit_lession' lession.id %}" method="POST">
            {% csrf_token %}
            <!--  -->
            {{form.media}}
            <!--  -->
            {{form.as_p}}
            <input class="btn btn-primary col-12 col-lg-2" type="submit" value="Save Changes" />
        </form>
    </section>
</div>

<!--  -->
{% endblock body %}

MasterSite/masterusers/templates/masterusers/lession_details.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}lession details{% endblock title %}

<!-- body -->
{% block body %}
<div style="background-color:#fff;">
    <div class="container">
        <div class="lession-details-wrapper">
            <p>
                {{lession.lession|safe}}
            </p>
        </div>
    </div>
    <!--  -->
</div>
<a href="{% url 'masteruser:topics_lessions' topic_lession.subject.id %}" class="btn btn-info mt-1 text-center">Other Lessions of {{topic_lession.subject.name}}</a> {% endblock body %}

MasterSite/masterusers/templates/masterusers/profile.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}profile{% endblock title %}

<!-- body -->
{% block body %}
<div class="profile-wrapper">
    <section id="profile-header">
        <h1>In Profile</h1>
        <div class="alert alert-info alert-dismissible fade show text-center" role="alert">
            <strong>Hollo</strong> You are welcome.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </section>
    <section class="profile-content-wrapper">
        <div class="new-subject-wrapper">
            <section id="new-subjection-info">
                <h2>Add New Subject To Learn</h2>
            </section>
            <!-- form area -->
            <section class="new-subject-form">
                <form action="{% url 'masteruser:profile' %}" method="POST" class="form-group">
                    {% csrf_token %}
                    <!--  -->
                    <div class="input-group col mb-3">
                        {{form}}
                    </div>
                    <input type="submit" class="btn btn-success btn-md col-12" value="Add" />
                </form>
            </section>
        </div>
        <!-- main content area -->
        <div class="panel panel-default">
            <h3>My Subjects</h3>
            <div class="panel-body">
                {% for subject in subjects %}
                <!--  -->
                <div class="panel-danger ml-3">
                    <a href="{% url 'masteruser:topics_lessions' subject.id %}">{{subject}}</a>
                </div>
                {% endfor %}
            </div>

        </div>
    </section>

</div>
<!--  -->
{% endblock body %}

MasterSite/masterusers/templates/masterusers/topic_and_lessions.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}details{% endblock title %}

<!-- body -->
{% block body %}
<div class="main-wrapper">
    <!--  -->
    <section class="container">
        <h1>
            <a class="btn btn-primary" href="{% url 'masteruser:profile' %}"> profile</a>
        </h1>

    </section>
    <section class="mb-3">
        <form action="{% url 'masteruser:topics_lessions' subject.id %}" class="new-lession-form" method="POST">
            {% csrf_token %}
            <!--  -->
            {{form.as_p}}
            <!--  -->
            <input class="btn btn-success col-12 col-sm-2" type="submit" value="Add">
        </form>
    </section>
    <section class="container">
        <h1 class="text-uppercase text-center mb-3">{{subject}} <span class="text-capitalize text-success">learning materials</span></h1>
        <div class="row">
            {% for topic in topics %}
            <div class="card mb-3">
                <div class="card-header row align-items-start">
                    <div class="col">
                        <h3>{{topic.topic_name}}</h3>
                    </div>
                    <div class="col">
                        <a href="{% url 'masteruser:add_new_lession' topic.id %}" class="btn btn-info">Add New Lession</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'masteruser:delete_topic' topic.id %}" class="btn btn-danger">Delete Topic</a>
                    </div>

                </div>
                <div class="card-body">
                    {% for lession in topic.learn_set.all %}
                    <!--  -->
                    <div class="lession-type">
                        <h3>{{lession.lession_type}}</h3>
                        <span>
                            <a href="{% url 'masteruser:edit_lession' lession.id %}" class="btn btn-primary">Edit</a>
                            <a href="{% url 'masteruser:delete_lession' lession.id %}" class="btn btn-danger">Delete</a>
                        </span>
                    </div>
                    <div class="lession-detailed">
                        <p>{{lession.lession|safe|truncatechars:50}}
                            <span>
                                <a href="{% url 'masteruser:lession_details' lession.id %}" class="btn btn-info">read all</a>
                            </span>
                        </p>
                    </div>
                    <!--  -->
                    {% endfor %}
                </div>

            </div>
            {% endfor %}
        </div>
    </section>

</div>


<!--  -->
{% endblock body %}