MasterSite/masterusers/urls.py
from django.urls import path

# ================ imports from current app
from . import views as user_web_views

# ================== app's name ================

app_name = "masteruser"
urlpatterns = [
    # =========================== profile =====================
    path('master/user/profile',user_web_views.profile,name="profile"),

    # =================== subjects learns =============================
    path('master/user/subjects/<int:subject_id>/learns',user_web_views.topics_and_lessions,name='topics_lessions'),
    path('master/user/subject/<int:topic_id>/topic/add',user_web_views.add_lession,name="add_new_lession"),
    path('master/user/subjects/lession-<int:lession_id>/details',user_web_views.lession_details,name="lession_details"),
    path('master/user/subject/lession-<int:lession_id>/edit',user_web_views.edit_learns,name="edit_lession"),
    path('user/topic/<int:topic_id>/delete',user_web_views.delete_topic,name='delete_topic'),
    path('user/lession/<int:lession_id>/remove',user_web_views.delete_lession,name="delete_lession"),

]

MasterSite/masterweb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("masterwebsite.urls")),
    path('master/users',include("masterusers.urls")),
    path('ckeditor/',include("ckeditor_uploader.urls")),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MasterSite/masterwebsite/urls.py
from django.urls import path

# ================ imports from current app
from . import views as web_views

# ================== app's name ================

app_name = "master"
urlpatterns = [
    path('',web_views.index,name="home"),
    # ====================== programming questions ,answers and comments =====================
    path('master/languages',web_views.languages,name='programming_languages'),
    path('master/add_language',web_views.add_language,name='add_language'),
    path('master/language/<int:language_id>/questions',web_views.languages_questions,name='language_questions'),
    path('master/question/<int:question_id>answers',web_views.question_answers,name='question_answers'),
    path('ask-question/',web_views.ask_question,name='ask_question'),
    path('add/response/to/<int:question_id>',web_views.add_response,name='add_response'),
    path('add/comments/<int:solution_id>',web_views.add_comment,name="add_comment"),
    path('all/comments/<int:solution_id>',web_views.all_comments,name="all_comments"),
]

MasterSite/masterwebsite/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

# =============================== programming codes models ==============================
class ProgrammingLanguage(models.Model):
    """ programming languages whose questions are solved"""
    language_name = models.CharField("Language Name",max_length=25,null=False,blank=False)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.language_name


class Question(models.Model):
    """question to be answered """
    programming_language = models.ForeignKey(ProgrammingLanguage,on_delete=models.CASCADE)
    question_text = models.TextField(verbose_name="Question",blank=False,null=False)


    def __str__(self):
        """ to be modified to question by username"""
        return self.question_text[:50]


class ProgramSolutions(models.Model):
    """ program solution to a question asked """
    # a question can have many solution from different users
    # user model as a foreignkey
    # language name as a foreignkey
    # language_name = models.ForeignKey(ProgrammingLanguage,on_delete=models.CASCADE)
    program_question = models.ForeignKey(Question,on_delete=models.CASCADE)
    solution_code = RichTextUploadingField(blank=False,null=False,config_name='special')

    class Meta:
        verbose_name_plural = "Programm Solutions"

    def __str__(self):
        """ to be modified to question_text+user_name"""
        return "Solution To "+self.program_question.question_text

class Comment(models.Model):
    """ comments of the solution to the question """
    # program solution as a foreign key
    program_solution = models.ForeignKey(ProgramSolutions,on_delete=models.CASCADE)
    comment_text = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text[:20]
    
# =============================================== programming code models ends here ================\

MasterSite/masterwebsite/forms.py
from django import forms
# ================ user learns models import ===programming questions models import =======
from .models import (
                    ProgrammingLanguage,
                    ProgramSolutions,
                    Comment,
                    Question,
                    )

# =================== Programming questions, answers and comments forms ============= 

class ProgrammingLanguageForm(forms.ModelForm):
    class Meta:
        model = ProgrammingLanguage
        fields = ['language_name']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields=['programming_language','question_text']


class ProgramSolutionForm(forms.ModelForm):
    class Meta:
        model = ProgramSolutions
        fields =['solution_code']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

MasterSite/masterwebsite/views.py
from django.shortcuts import render,redirect,get_object_or_404

# Create your views here.
from .models import (
                    ProgramSolutions,
                    ProgrammingLanguage,
                    Question,
                    )
from .forms import (
                    # ============== program questions,answers and commnents forms ===============
                    ProgrammingLanguageForm,
                    ProgramSolutionForm,
                    QuestionForm,
                    CommentForm,
                    )

def index(request):
    """home"""
    languages= ProgrammingLanguage.objects.order_by('-date_added').all()
    context={
        "languages":languages,
    }
    return render(request,"master/index.html",context)



# ============================= Questions Asked and their answers and comments here ===============
def ask_question(request):
    """ ask a question about a language you want it to be written in"""
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
                question_form.save()
                return redirect("master:home")     
    else:
        question_form = QuestionForm()

    context = {
        'question_form':question_form
    }
    return render(request,"master/ask_question.html",context)

def add_language(request):
    """ Add new language """
    if request.method == "POST":
        form = ProgrammingLanguageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("master:ask_question")
    else:
        form = ProgrammingLanguageForm()
    context = {
        'form':form,
    }

    return render(request,"master/add_language.html",context)

def languages(request):
    """ all languages"""
    languages = ProgrammingLanguage.objects.all()
    context = {
        "languages":languages,
    }
    return render(request,"master/languages.html",context)

def languages_questions(request,language_id):
    """ all questions about a language """
    language = get_object_or_404(ProgrammingLanguage,pk=language_id)
    context = {
        "language":language,
    }
    return render(request,"master/language_questions.html",context)

def question_answers(request,question_id):
    """ all answers to a qustion"""
    question = get_object_or_404(Question,pk=question_id)
    context = {
        "question":question,
    }
    return render(request,'master/question_answers.html',context)


def add_response(request,question_id):
    """ add your response to a question desire"""
    question = get_object_or_404(Question,pk=question_id)
    if request.method == "POST":
        form = ProgramSolutionForm(request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            response.program_question = question
            response.save()
            return redirect('master:home')
    else:
        form = ProgramSolutionForm()
    context = {
        'question':question,
        'form':form,
    }
    return render(request,'master/add_response.html',context)

# ======================= comments section =========================

def add_comment(request,solution_id):
    """add comment to the solution"""
    solution = get_object_or_404(ProgramSolutions,pk=solution_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.program_solution = solution
            new_comment.save()
            return redirect("master:home")
    else:
        form = CommentForm()
    
    context={
        'form':form,
        'solution':solution,
    }
    return render(request,'master/add_comment.html',context)

def all_comments(request,solution_id):
    """show all comments of a solution"""
    solution = get_object_or_404(ProgramSolutions,pk=solution_id)
    return render(request,'master/all_comments.html',
    context={"solution":solution,
    })
# ============================= Questions Asked and their answers and comments ends here ============

MasterSite/masterwebsite/templates/master/add_comment.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}Home{% endblock title %}

<!-- body -->
{% block body %}
<!--  -->
{% for comment in solution.comment_set.all %}
<!--  -->
{{comment.comment_text}}
<!--  -->
{% endfor %}
<form action="{% url 'master:add_comment' solution.id %}">
    <!--  -->
    {% csrf_token %}
    <!--  -->
    {{form.as_p}}
    <input type="submit" value="comment" />
</form>
<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/add_language.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}question answers{% endblock title %}

<!-- body -->
{% block body %}
<!--  -->
<div class="new-language">
    <form action="{% url 'master:add_language' %}" method="POST">
        <!--  -->
        {% csrf_token %}
        <!--  -->
        {{form.as_p}}
        <input type="submit" value="add language" />
    </form>
</div>

<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/add_response.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}add response{% endblock title %}

<!-- body -->

<!-- body -->
{% block body %}
<div class="response-wrapper">
    <section class="response-form">
        <form action="" method="POST">
            {% csrf_token %}
            <!--  -->
            {{form.media}}
            <!--  -->
            {{form.as_p}}
            <!--  -->
            <input class="btn btn-success col-5" type="submit" value="Add Response">
        </form>
    </section>
</div>

<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/all_comments.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}all comments{% endblock title %}

<!-- body -->
{% block body %}
<!--  -->
<div class="all-comment-wrapper">
    {% for comment in solution.comment_set.all%}
    <!--  -->
    {{comment.comment_text}}
    <!--  -->
    <a href="#">like</a>
    <!--  -->
    {% endfor %}
</div>
<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/ask_question.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}ask question{% endblock title %}

<!-- body -->
{% block body %}
<div class="questions-wrapper">
    <p>If language amoung in dropdown click here to <a href="{% url 'master:add_language' %}">Add Language</a></p>
    <section class="questions-form">
        <form action="{% url 'master:ask_question' %}" method="POST">
            {% csrf_token %}
            <!--  -->
            {{question_form.as_p}}
            <!--  -->
            <input type="submit" value="Ask Question">
        </form>
    </section>
</div>

<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/base.html
<!DOCTYPE html> {% load static i18n %}
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--  -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.5.0/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.5.0/build/highlight.min.js"></script>

    <script>
        hljs.initHighlightingOnLoad();
    </script>
    {% include 'master/nav_links.html' %}
</head>

<body style="background: rgb(236, 240, 239);">
    <div width="100%" height="320px">
    </div>

    <div class="container">
        {% block body %}{% endblock body %}
    </div>
    {% include 'master/footer_links.html' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

</body>

</html>

MasterSite/masterwebsite/templates/master/footer_links.html
<div class="footer-wrapper" width="100%" height="3000px">
    <footer>
        Copyright &copy; mASTER pROGRAMMING
    </footer>
</div>

MasterSite/masterwebsite/templates/master/index.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}Home{% endblock title %}

<!-- body -->
{% block body %}
<div class="main-wrapper">
    <!--  -->
    <section id="main-hearder">
        <h1>Main</h1>
    </section>
    <div class="languages-section-wrapper">
        <a class="btn btn-info" href="{% url 'master:programming_languages' %}" class="languages-link">master languages</a>
    </div>

</div>


<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/language_questions.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}language questions{% endblock title %}

<!-- body -->
{% block body %}
<div class="language-questions-wrapper">
    <div class="row">
        {% for question in language.question_set.all %}
        <!--  -->
        <div class="col">
            <div class="card">
                <p class="card-body">
                    <a href="{% url 'master:question_answers' question.id %}">{{question.question_text}}</a>
                </p>

                <p class="card-header" style="display: grid;grid-template-columns:repeat(3,1fr); gap:3em; padding-left:40px;">
                    <a class="btn btn-success" href="{% url 'master:add_response' question.id %}">Respond</a>
                    <a class="btn btn-primary" href="#">Edit Response</a>
                    <a class="btn btn-danger" href="#">Delete Response</a>
                </p>
            </div>
        </div>
        <!--  -->
        {% endfor %}
    </div>
</div>
<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/languages.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}edit-lession-type{% endblock title %}


<!-- body -->
{% block body %}
<div class="row">
    {% for language in languages %}
    <!--  -->
    {% if language.question_set.count > 0 %}

    <!--  -->
    <div class="col-12 col-lg-6 mb-3 ">
        <div class="card text-center">
            <div class="card-header">
                <a href="{% url 'master:language_questions' language.id %}" class="text-success active text-uppercase">{{language}}</a>
            </div>
            <div class="card-body">
                <h5 class="card-title">This Are Some Questions About {{language}}</h5>
                <p class="card-text">This questions and their solutions will help you learn <strong>{{language}}</strong> without difficulties.</p>
                <a href="{% url 'master:language_questions' language.id %}" class="btn btn-primary">Asked Questions</a>
            </div>
        </div>
    </div>
    {% endif %}
    <!--  -->
    {% endfor %}
</div>
<!--  -->
{% endblock body %}

MasterSite/masterwebsite/templates/master/nav_links.html
<div class="main-nav">
    <nav class="navbar navbar-expand-lg mb-3 navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'master:home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'masteruser:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'master:ask_question' %}">Ask Question</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Pricing</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item navbar-link" href="#">Action</a></li>
                            <li><a class="dropdown-item navbar-link" href="#">Another action</a></li>
                            <li><a class="dropdown-item navbar-link" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

MasterSite/masterwebsite/templates/master/question_answers.html
{% extends 'master/base.html' %}
<!-- title -->
{% block title %}question answers{% endblock title %}

<!-- body -->
{% block body %}
<!--  -->
<div style="background-color:#fff;">
    <div class="container">
        {{question.question_text}}
        <!--  -->
        {% for answer in question.programsolutions_set.all %}
        <!--  -->
        <p>{{answer.solution_code|safe}}</p>
        <!--  -->
        <div class="add-comment">
            <a class="btn btn-success mb-3" href="{% url 'master:add_comment' answer.id %}">Add Comment</a>
            <a class="btn btn-primary  mb-3" href="{% url 'master:all_comments' answer.id %}">all comments</a>
        </div>
        {% endfor %}
    </div>
</div>
<!--  -->
{% endblock body %}